### ISSUE TITLE
Cask refactor broke all formulas depending on the plugin formula

### ISSUE THREAD

**Issue by capelio** [syncdk/homebrew-aws-session-manager-plugin#12]
Heya @dkanejs. First off, thanks for all the hard work supporting this Brew formula. It's been very useful to be able to depend on it from other formulas.

Unfortunately, with the cask refactor, any new installs of fomulas that depended on the fomula-version of the plugin now fail. I've scoured the Homebrew docs and it's not possible to depend on a cask from a formula. It's also not possible to specify a git hash or tag via `depends_on`.

Any chance you could re-introduce the formula version of the plugin alongside the cask version?

**Comment by Systemmanic** [comment]
Hey @capelio,

First of all, thanks and apologies for breaking your stuff, wasn't intentional of course.

I had just assumed now it is in Cask that no one would want to go to the trouble of using mine 😆

I will reinstate this plugin back as a brew one asap, I had not considered your use case!

**Comment by Systemmanic** [comment]
I've merged #13 so that's it back in action @capelio 

It's on the latest available version now also: `1.1.50.0`

I'm happy to maintain this version regardless of the Cask version existing in `homebrew-cask`, especially if it covers a dependencies use case.

Let me know if that's working for you and we can get this one closed 😄

**Comment by Systemmanic** [comment]
Closing this as I believe this is fixed, feel free to reopen if required.
